### ISSUE TITLE
Failed to compile on linux

### ISSUE THREAD

**Issue by chromer030** [z3APA3A/3scan#1]
`[Arch@Linux 3scan-master]$ gcc -o3scan 3scan.c`
`/usr/bin/ld: /tmp/ccU1cE8c.o: in function `main':`
`3scan.c:(.text+0x27a6): undefined reference to `pthread_create'`
`/usr/bin/ld: 3scan.c:(.text+0x2869): undefined reference to `pthread_create'`
`/usr/bin/ld: 3scan.c:(.text+0x28a1): undefined reference to `pthread_create'`
`/usr/bin/ld: 3scan.c:(.text+0x28d9): undefined reference to `pthread_create'`
`/usr/bin/ld: 3scan.c:(.text+0x2911): undefined reference to `pthread_create'`
`/usr/bin/ld: /tmp/ccU1cE8c.o:3scan.c:(.text+0x2949): more undefined references to `pthread_create' follow`
`collect2: error: ld returned 1 exit status`

**Comment by z3APA3A** [comment]
try

`gcc -fPIE -O2 -fno-strict-aliasing -pthread -o3scan 3scan.c`

**Comment by chromer030** [comment]
compiled successfully with `gcc -fPIE -O2 -fno-strict-aliasing -pthread -o3scan 3scan.c`
